services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=you_note_db'
      - 'POSTGRES_PASSWORD=123456789'
      - 'POSTGRES_USER=db_user'
    ports:
      - '7756:5432'
